# Generated by Django 2.0 on 2019-08-06 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('location_accuracy_radius', models.IntegerField(blank=True, null=True)),
                ('location_latitude', models.FloatField(default=0.0)),
                ('location_longitude', models.FloatField(default=0.0)),
                ('location_metro_code', models.IntegerField(blank=True, null=True)),
                ('location_time_zone', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ipaddress')),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('country_iso_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
